### ISSUE TITLE
[Feature Request] support load multiple .env files

### ISSUE THREAD

**Issue by aprilahijriyan** [cardinalby/export-env-action#3]
Hi, thanks in advance for creating this github action. This is very helpful on a project I'm working on. 

In my case I have 2 .env files, so I have to make 2 steps to load those files. 
Maybe it would be great if 1 step could load multiple files?

Thanks.

**Comment by cardinalby** [comment]
Hi and thanks for the interest for my action!

I have taken a look at your request. It's possible to implement, but from architectural point of view it's not the best option, I believe. It will complicate the action logic and will make it less clear for users: we need to consider interference with `expand` and `expandWithJobEnv` inputs: whether we should expand variables in second file by the values from the first one or not (and implement proccess.env isolation in this case). For this cases Readme and tests should be updated accordingly.

That's why I suggest keeping using 2 steps: it will be more explicit and clear, even though more verbose. If you have more than 2 files (or unknown number of files) you can use preparation step to join them to 1 temp file (`cat *.env >> concatenated.env`) and pass it to the action.
